import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "@/components/ui/sonner";

const avenirNext = localFont({
  src: [
    {
      path: "../../fonts/avenirnext-medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/avenirnext-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../fonts/avenirnext-heavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-avenir-next",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenirNext.variable} antialiased`}>
        <NuqsAdapter>{children}</NuqsAdapter>
        <Toaster />
      </body>
    </html>
  );
}
